<?xml version="1.0" encoding="utf-8"?><Database Name="RSA" Class="RSADataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-HLH7NCP\SQLEXPRESS;Initial Catalog=RSA;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="RSAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RSAtable" Member="RSAtables">
    <Type Name="RSAtable">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="encryptedText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="n" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="e" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>